version: '3'
services:
  eureka:
    image: eureka
    ports:
      - 8761:8761
  gateway:
    image: gateway
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://eureka:8761/eureka
         -Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - eureka
    ports:
      - 8081:8081
  user-service:
    image: userservice
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    depends_on:
      - eureka
      - gateway